experiment:
    id: fasterrcnn 
    seed: 1324

checkpoint: ''
tensorboard: ''

##Data
data:
    train: ''
    val: ''

##Training
train:
    n_gpus: 1
    workers: 0 
    max_epoch: 200
    batch_size: 6
    n_classes: 3
    overfit: False
    lr: 0.0001

val:
    nms_th: 0.4
    prob_th: 0.0
